### ISSUE TITLE
Please invite me to the Jec-Forge GitHub Community Organization

### ISSUE THREAD

**Issue by idimetrix** [Jec-Forge/support#16]
### Name

Dmitrii Selikhov

### Discord Username (if applicable)

idimetrix

### Additional Context

I'm open source advocate and love to do open source contributions:

🚀CTO, 🏗️Software Architect, 🧑‍💻Technical Lead, 👨‍💼3X Founder. 🔗Linking companies with top tech talents.

CV: [https://dmitrii-selikhov.vercel.app](https://dmitrii-selikhov.vercel.app)
GitHub: [https://github.com/idimetrix](https://github.com/idimetrix)
LinkedIn: [https://www.linkedin.com/in/dimetrix](https://www.linkedin.com/in/dimetrix)

### Record

- [ ] Yes, I am from JEC.
- [ ] I complete my Graduation from JEC.
- [X] I'm a Web Developer.
- [ ] I'm a Flutter Developer.
- [X] I'm a DevOps Engineer.
- [X] Cyber Security Expert
- [X] I'm not from JEC, but I want to join the organization for interaction and collaboration.

**Comment by mdazfar2** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Jec-Forge/people<br><br>
